parameters:
#    shop_shop.example.class: Shop\ShopBundle\Example
    shop_shop_security.component.authentication.handler.login_success_handler.class: Shop\ShopBundle\Component\Authentication\Handler\LoginSuccessHandler
    shop_shop_security.component.authentication.handler.logout_success_handler.class: Shop\ShopBundle\Component\Authentication\Handler\LogoutSuccessHandler

services:
#    shop_shop.example:
#        class: %shop_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    acme_user.registration.form.type:
        class: Shop\ShopBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: shop_user_registration }
            
    acme_user.profile.form.type:
        class: Shop\ShopBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: shop_user_profile }
    
    shop.login.event.listener:
      class: Shop\ShopBundle\EventListener\LoginListener
      arguments: ["@doctrine"]
      tags:
        - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }      
        
    shop_shop_security.component.authentication.handler.login_success_handler:
      class: %shop_shop_security.component.authentication.handler.login_success_handler.class%
      arguments: ['@router','@security.context']
      tags:
        - { name: 'monolog.logger', channel:'security' }
        
    shop_shop_security.component.authentication.handler.logout_success_handler:
      class: %shop_shop_security.component.authentication.handler.logout_success_handler.class%
      arguments: ['@router', '@security.context']
      tags:
        - { name: 'monolog.logger', channel:'security' }
      

